[pytest]
pythonpath =
    systems/order
    systems/order/shared
    systems/market-data/shared
    systems/agent-orchestration/shared
    systems/fundamentals/shared
    systems/api-server/pods/api-server
    .
testpaths =
    systems/api-server/tests
    systems/agent-orchestration/tests
    systems/fundamentals/tests
    systems/market-data/tests
    systems/order/tests
addopts = -ra --import-mode=importlib
