apiVersion: v1
kind: ServiceAccount
metadata:
  name: alfaka-market-data-sa
  namespace: alfaka-market-data
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<aws-account-id>:role/alfaka-dev-market-data-irsa
