apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: cache-db
spec:
  replicas: 1
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 10m
    consolidationPolicy: WhenEmpty
  template:
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: eks.amazonaws.com/instance-family
          operator: In
          values:
            - m5a
            - m6a
        - key: eks.amazonaws.com/instance-cpu
          operator: In
          values:
            - "4"
        - key: eks.amazonaws.com/instance-memory
          operator: In
          values:
            - "16384"
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - key: gops.io/dedicated
          value: cache-db
          effect: NoSchedule
      terminationGracePeriod: 24h0m0s
