apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: gops-app-agent-50
spec:
  role: AmazonEKSAutoNodeRole
  subnetSelectorTerms:
    - tags:
        name: gops-vpc
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: gops-eks-cluster
  ephemeralStorage:
    size: 50Gi
    iops: 3000
    throughput: 125
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  snatPolicy: Random
